name: on_delivery
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  webview_flutter: ^1.0.1
  flutter_credit_card: ^0.1.3
  http:
  flutter_polyline_points:
  lottie:
  firebase_messaging:
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications:
  country_list_pick: ^1.0.1+4
  firebase_core:
  firebase_auth:
  firebase_database:
  cloud_firestore: ^0.14.2
  firebase_storage:
  http_auth: ^0.3.2
  expand_widget:
  pinput: ^0.2.6
  rxdart: ^0.25.0
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  google_sign_in:
  cached_network_image:
  flutter_launcher_icons: 0.7.5
  flutter_google_places:

  stripe_payment: ^1.1.1
  flutter_places_autocomplete:
  geocoder: ^0.2.1
  location: ^3.0.0
  custom_switch:
  lite_rolling_switch: ^0.1.1
  permission_handler: ^3.0.0
  url_launcher: ^5.7.10
  font_awesome_flutter: 8.8.1
  gradient_text: 1.0.2
  image_picker: ^0.6.7+12
  flare_flutter:
  random_color: ^1.0.5
  ff_navigation_bar: ^0.1.5
  responsive_builder: ^0.2.0+2
  marquee: ^1.5.2
  camera: ^0.5.8+2
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  open_file: ^3.0.1
  wakelock:
  flutter_svg:
  date_range_picker: ^1.0.5
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  dio: ^3.0.10
  uuid: 2.0.1
  timeago: ^2.0.28
  cupertino_icons: ^1.0.2
  image_cropper: ^1.3.1
  flutter_icons: ^1.1.0
  percent_indicator: ^2.1.8
  fluttertoast: ^7.1.1
  animations: ^1.1.2
  image: ^2.1.18
  google_fonts: ^1.1.1
  provider:
  flutter_bloc:
  modal_progress_hud: ^0.1.3
  flutter_facebook_auth: ^2.0.2
  flutter_facebook_login: ^3.0.0
  screen: ^0.0.5 # keeping screen on

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mylocationmarker.png"
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

